# Welcome to Jekyll!
#
# Basic Site Settings
locale                   : "en-US"
title                    : "Ryan Lucas"
title_separator          : "-"
name                     : &name "Ryan Lucas"
description              : &description "PhD Student at MIT Operations Research Center"
url                      : "https://ryanlucas3.github.io"
baseurl                  : ""
repository               : "ryanlucas3/ryanlucas3.github.io"

# Site Author
author:
  avatar           : "profile.png"
  name             : "Ryan Lucas"
  bio              : "PhD Student at MIT Operations Research Center"
  location         : "Cambridge, MA"
  googlescholar    : "https://scholar.google.com/citations?user=NzylXAgAAAAJ&hl=en"
  github           : "https://github.com/ryanlucas3"

# Site Settings
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Markdown Processing
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
